name: 'test-action-1'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: activity
  color: gray-dark